# Generated by Django 6.0.1 on 2026-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.ImageField(upload_to=''),
        ),
    ]
