# Generated by Django 6.0.1 on 2026-02-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offerdetail_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer/'),
        ),
    ]
