# Generated by Django 6.0.1 on 2026-02-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='description',
        ),
    ]
