# Generated by Django 6.0.1 on 2026-02-12 09:36

import django.core.validators
import profiles_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_alter_profile_location_alter_profile_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Use HH-HH format (0–23), e.g. 10-18', regex='^(?:[0-9]|1[0-9]|2[0-3])-(?:[0-9]|1[0-9]|2[0-3])$'), profiles_app.models.working_hours_logic]),
        ),
    ]
